# Netlify Configuration File for IWA™

# This is a "redirect" rule.
[[redirects]]
  # When a user goes to the root of your site (e.g., https://iwa-official.netlify.app/)
  from = "/"
  
  # Show them the main.html page instead.
  to = "/main.html"
  
  # The status "200" means "OK". This is a rewrite, not a redirect,
  # so the user's browser URL will stay clean (it won't show /main.html).
  status = 200